version: "3.9"

services:

  database:
    container_name: database
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "azerty123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
