version: "3.9"

services:

  database:
    container_name: database
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "azerty123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  webapi:
    container_name: webapi
    build: ./webapi
    ports:
      - "5000:80"
    depends_on:
      - database
    environment:
      SQL__ConnectionString: "Server=database;Database=model;User Id=SA;Password=azerty123!;Encrypt=False;TrustServerCertificate=True;"

  reactapp:
    container_name: reactapp
    build: ./reactapp
    ports:
      - "3000:80"
    depends_on:
      - webapi
    environment:
      REACT_APP_API_PROXY: "http://webapi:80/"