IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Expense')
BEGIN
    DROP TABLE Expense;
END

CREATE TABLE Expense
(
    Id INT PRIMARY KEY IDENTITY,
    Date DATETIME NOT NULL,
    Amount DECIMAL(18, 2) NOT NULL,
    Recipient NVARCHAR(255) NOT NULL,
    Currency NVARCHAR(10) NOT NULL,
    Type INT NOT NULL
);
